addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")
addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.8.2")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "0.5.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.23")